import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import NavBar from "@/components/navigation/nav-bar";
const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  variable: "--font-spartan",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("font-sans antialiased", leagueSpartan.variable)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="mt-16">
            <NavBar />
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
